# Setup
---
version: '3.5'
services:


# Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      PUID: '0'
      PGID: '0'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/sonarr:/config'
      - '/media/media/TV Shows:/media/media/TV Shows'
      - '/media/media/downloads/TV:/media/media/downloads/TV'
    ports:
      - '8989:8989'
    restart: unless-stopped

# Overseerr
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: America/New_York
    volumes:
      - '/opt/appdata/overseerr:/app/config'
    ports:
      - '5055:5055'

# Radarr
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    hostname: radarr
    environment:
      PUID: '0'
      PGID: '0'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/radarr:/config'
      - '/media/media/downloads/Movies:/media/media/downloads/Movies'
      - '/media/media/Movies:/media/media/Movies'
    ports:
      - '7878:7878'
    restart: unless-stopped