# Setup
---
version: '3.5'
services:

# Plex
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: sonarr
    environment:
      - PUID: '1000'
      - PGID: '1000'
      - TZ: America/New_York
      - VERSION: 'docker'
    volumes:
      - /opt/appdata/plexmediaserver:/config
      - /media:/media 
    ports:
      - '32400:32400'
    restart: unless-stopped

# Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      PUID: '0'
      PGID: '0'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/sonarr:/config'
      - '/media/media/TV Shows:/media/media/TV Shows'
      - '/media/media/downloads/TV:/media/media/downloads/TV'
    ports:
      - '8989:8989'
    restart: unless-stopped

# Radarr
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    hostname: radarr
    environment:
      PUID: '0'
      PGID: '0'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/radarr:/config'
      - '/media/media/downloads/Movies:/media/media/downloads/Movies'
      - '/media/media/Movies:/media/media/Movies'
    ports:
      - '7878:7878'
    restart: unless-stopped

    # Overseerr
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      TZ: America/New_York
    volumes:
      - '/opt/appdata/overseerr:/config'
    ports:
      - '5055:5055'

# Tautulli
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/tautulli:/config/'
      - '/media/backup/tautulli:/backup'
    ports:
      - '8181:8181'
    restart: unless-stopped

# Prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/prowlarr:/config/'
    ports:
      - '9696:9696'
    restart: unless-stopped

# NZBGet
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
    volumes:
      - '/opt/appdata/nzbget:/config/'
      - '/media/media/downloads:/media/media/downloads'
    ports:
      - '6789:6789'
    restart: unless-stopped

# TDARR Server
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr_server
    hostname: tdarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/New_York
    volumes:
      - '/opt/tdarr/server:/app/server'
      - '/media/media:/media'
      - '/media/media/Cache:/temp'
      - '/opt/tdarr/configs:/app/configs'
      - '/opt/tdarr/logs:/app/logs'
    ports:
      - '8265-8267:8265-8267'
    restart: unless-stopped

# Ouroboros
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    hostname: ouroboros
    restart: unless-stopped
    environment:
      LOG_LEVEL: 'info'
      SELF_UPDATE: 'true'
      CLEANUP: 'true'
      INTERVAL: '300'
      TZ: 'America/New_York'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'