# #Ombi
# ---
# version: '3.5'
# services:
#   ombi:
#     image: ghcr.io/linuxserver/ombi:latest
#     container_name: ombi
#     hostname: ombi
#     environment:
#       PUID: '1000'
#       PGID: '1000'
#       TZ: America/New_York
#     volumes:
#       - '/opt/appdata/ombi/config:/config'
#     ports:
#       - '3579:3579'
#     restart: unless-stopped